### ISSUE TITLE
Writeable glossary entries no longer displayed in bold

### ISSUE THREAD

**Issue by didierbr** [hiohiohio/omegat-plugin-linkbuilder#1]
Hello,

When using the linkbuilder plugin, writeable glossary entries are no longer displayed in bold. It is rather obvious visually: the glossary entries are first displayed in bold when opening the project, and are re-displayed without bold immediately after that.

Didier

**Comment by kosivantsov** [comment]
I confirm the behavior.

Kos

**Comment by hiohiohio** [comment]
Hi Didier,
Thank you for the feedback. Yes, currently I just clear all styles on the pane before applying link actions.
I will try to find solution to solve this problem.

Hi Kos,
Thank you for the checking this problem.

Kind Regards,
Chihiro

**Comment by didierbr** [comment]
Thank you. It works fine now.

Didier
