### ISSUE TITLE
Integrate into OmegaT

### ISSUE THREAD

**Issue by amake** [hiohiohio/omegat-plugin-linkbuilder#2]
I think this plugin represents an important feature and I would like to integrate it into the main OmegaT project. Would you be willing to contribute your code under GPLv3?

**Comment by hiohiohio** [comment]
Hi Aaron, I have made a new branch for GPLv3. Hope it helps you. Please note that I have used two components which are written by other people (please see BareBonesBrowserLaunch.java and JTextPaneAttributeInserter.java).

**Comment by amake** [comment]
Thanks very much! I made a few changes and have prepared a patch to add the modified version of your component to the main project:

https://sourceforge.net/p/omegat/code/ci/b5f0e54e97f0ecc919dacab995f76fb3b7aede9e/

Are you OK with this in terms of attribution? I also plan to make an RFE and note the change in changes.txt with a mention of you and this project.

**Comment by hiohiohio** [comment]
Thank you for the integration. It looks good to me. I will add a note on the readme of this plugin about this integration when the integrated version of OmegaT is released.

**Comment by amake** [comment]
Thanks again. The patch is applied to trunk. It will be included in the next release, which will be 3.5.3.
